### ISSUE TITLE
does it work on windows?

### ISSUE THREAD

**Issue by AquariusPower** [skeeto/fantasyname#10]
hi!
great name generator!

we are trying to use it at ivan https://github.com/Attnam/ivan/pull/363
on linux is working great, but on windows is outputting empty names,

any tips?

**Comment by skeeto** [comment]
Thanks! The author of the C++ version is @Kronuz.

It looks like the problem is Mingw-w64's version of mbsrtowcs() is 
buggy. I've worked around this in 643d3a0.
