### ISSUE TITLE
Convert the code of namegen into a header-only library?

### ISSUE THREAD

**Issue by 1Hyena** [skeeto/fantasyname#12]
Similarly to https://github.com/nlohmann/json wouldn't it make sense for namegen to also consist of only a single header file (`namegen.h`) ? I know it's a matter of taste but for me personally those 1-header "libraries" have become really appealing lately. Anyone else thinking the same way?

**Comment by skeeto** [comment]
The C version is exactly what you want. It's written in plain old ANSI C 
and compiles cleanly under any C or C++ compiler (even as C++).

https://github.com/skeeto/fantasyname/blob/master/c/namegen.h

The API is a single function and there's no compilation step.

**Comment by 1Hyena** [comment]
@skeeto 
Nice! Didn't notice it earlier. The code is slightly more difficult to understand but perhaps there is no need to modify it anyway. I assume it just takes the name formula as an argument like the C++ version, so instead of adding more letters to `Generator::SymbolMap` I would just have to provide a longer and more complex formula, right?

**Comment by skeeto** [comment]
Yes, the template syntax is the same, except that it doesn't support 
reverse (~) and it has a maximum depth. As you noticed, the symbol 
tables are fixed and tightly packed, making it non-trivial manipulate. I 
might write a little ahead-of-time table compiler so you could more 
easily add custom symbols, but for now it's just the basic one. So, yes, 
you'd currently have to put your options into the template itself.

**Comment by 1Hyena** [comment]
Thanks for the info. Reverse (~) is not in my interest anyway. Closing this for now as it's indeed exactly what I was hoping for.
