### ISSUE TITLE
Incorrect name generation (C++)

### ISSUE THREAD

**Issue by skeeto** [skeeto/fantasyname#13]
@Kronuz, I've noticed that the C++ version often misses groups entirely, and the generated name is wrong. For example:

```
$ ./namegen '(a)(a)' 10
> combinations = 1
a
a
a
a
a
a
a
a
a
a
```

As far as I can tell, it's the second "a" that's missed. And this *only* seems to happen for certain letters (in both positions), like "a", "h", "i", "j", "q", "u", "v", "x", and "y" (and maybe more).

This comes up alternations, too:

```
$ ./namegen '(a)(b|a)' 10
> combinations = 2
a
ab
a
ab
ab
a
ab
a
ab
ab
```

That one is unable to generate "aa". I poked around in GDB trying to figure this out (where, unfortunately, it failed to pretty print any of the C++ objects), but had no luck so far.

**Comment by AquariusPower** [comment]
For more complex bigger names, like 2 names with more than 3 letters each, these still happen if you configure them to happen in between?
If that happens with names we could use, then patterns will fail when they shouldnt.

**Comment by skeeto** [comment]
@AquariusPower's comment about "ash" made me look at it differently and 
I figured it out. This is just the Collapser doing it's job. Check out 
the switch at line 330. So I guess this is intended. The JavaScript 
version doesn't do this.
