### ISSUE TITLE
Bookmarked URL with template?

### ISSUE THREAD

**Issue by MasterTMO** [skeeto/fantasyname#14]
Sorry, new to GitHub, if this isn't the proper way to ask questions.

I'd love to create my naming template string and then bookmark the page so I could just visit it on my phone or tablet without having to go through the effort of typing it in each time or saving the string in a memo or email and pasting it in each time.

Is something like this possible with minimal effort? Or even already possible and I just totally missed it?

Thanks for building this utility!!

TMO

**Comment by skeeto** [comment]
I thought it already had this feature, but I was thinking of another 
project. With this new feature, as you fill out the form it updates the 
page fragment, meaning you can bookmark it at any moment and it will 
remember the pattern. You can also share it with other people this way. 
For example:

https://nullprogram.com/fantasyname/#!%3Cv%7CBV%3ECs

**Comment by MasterTMO** [comment]
Sorry, it doesn't seem to be working now.  Also, does it understand the parentheses and pipe delimiters?  I hadn't gotten around to testing that before now.

Thanks again!

TMO

**Comment by MasterTMO** [comment]
Completely ignore that prior comment!  I have ScriptSafe on my browser, and the site hadn't been marked as safe, so it was blocking the script from running.  Sorry for the confusion!
